package Model;
// Generated 10 Oct 2019 3:43:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private String nrBi;
     private int codFuncionario;
     private String nomeCompleto;
     private String sexo;
     private String morada;
     private Date dataNascimento;
     private String departamento;
     private String cargo;
     private String contacto;
     private String email;
     private boolean status;
     private Set utilizadors = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int codFuncionario, String nomeCompleto, String sexo, String morada, Date dataNascimento, String departamento, String cargo, String contacto, String email, boolean status) {
        this.codFuncionario = codFuncionario;
        this.nomeCompleto = nomeCompleto;
        this.sexo = sexo;
        this.morada = morada;
        this.dataNascimento = dataNascimento;
        this.departamento = departamento;
        this.cargo = cargo;
        this.contacto = contacto;
        this.email = email;
        this.status = status;
    }
    public Funcionario(int codFuncionario, String nomeCompleto, String sexo, String morada, Date dataNascimento, String departamento, String cargo, String contacto, String email, boolean status, Set utilizadors) {
       this.codFuncionario = codFuncionario;
       this.nomeCompleto = nomeCompleto;
       this.sexo = sexo;
       this.morada = morada;
       this.dataNascimento = dataNascimento;
       this.departamento = departamento;
       this.cargo = cargo;
       this.contacto = contacto;
       this.email = email;
       this.status = status;
       this.utilizadors = utilizadors;
    }
   
    public String getNrBi() {
        return this.nrBi;
    }
    
    public void setNrBi(String nrBi) {
        this.nrBi = nrBi;
    }
    public int getCodFuncionario() {
        return this.codFuncionario;
    }
    
    public void setCodFuncionario(int codFuncionario) {
        this.codFuncionario = codFuncionario;
    }
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }
    
    public void setNomeCompleto(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getUtilizadors() {
        return this.utilizadors;
    }
    
    public void setUtilizadors(Set utilizadors) {
        this.utilizadors = utilizadors;
    }




}


