package Model;
// Generated 10 Oct 2019 3:43:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Levantamento generated by hbm2java
 */
public class Levantamento  implements java.io.Serializable {


     private Integer codLevantamento;
     private Parqueamento parqueamento;
     private Date data;
     private Date hora;
     private String nomeLevantamento;
     private Float preco;
     private boolean status;

    public Levantamento() {
    }

	
    public Levantamento(Parqueamento parqueamento, Date data, Date hora, String nomeLevantamento, boolean status) {
        this.parqueamento = parqueamento;
        this.data = data;
        this.hora = hora;
        this.nomeLevantamento = nomeLevantamento;
        this.status = status;
    }
    public Levantamento(Parqueamento parqueamento, Date data, Date hora, String nomeLevantamento, Float preco, boolean status) {
       this.parqueamento = parqueamento;
       this.data = data;
       this.hora = hora;
       this.nomeLevantamento = nomeLevantamento;
       this.preco = preco;
       this.status = status;
    }
   
    public Integer getCodLevantamento() {
        return this.codLevantamento;
    }
    
    public void setCodLevantamento(Integer codLevantamento) {
        this.codLevantamento = codLevantamento;
    }
    public Parqueamento getParqueamento() {
        return this.parqueamento;
    }
    
    public void setParqueamento(Parqueamento parqueamento) {
        this.parqueamento = parqueamento;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getNomeLevantamento() {
        return this.nomeLevantamento;
    }
    
    public void setNomeLevantamento(String nomeLevantamento) {
        this.nomeLevantamento = nomeLevantamento;
    }
    public Float getPreco() {
        return this.preco;
    }
    
    public void setPreco(Float preco) {
        this.preco = preco;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


