package Model;
// Generated 02 Oct 2019 12:30:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;

/**
 * Levantamento generated by hbm2java
 */
public class Levantamento  implements Serializable {


     private Integer codLevantamento;
     private Parqueamento parqueamento;
     private Calendar data;
     private Time hora;
     private String nomeLevantamento;
     private Float preco;
     private boolean status;

    public Levantamento() {
    }

	
    public Levantamento(Parqueamento parqueamento, Calendar data, Time hora, String nomeLevantamento, boolean status) {
        this.parqueamento = parqueamento;
        this.data = data;
        this.hora = hora;
        this.nomeLevantamento = nomeLevantamento;
        this.status = status;
    }
    public Levantamento(Parqueamento parqueamento, Calendar data, Time hora, String nomeLevantamento, Float preco, boolean status) {
       this.parqueamento = parqueamento;
       this.data = data;
       this.hora = hora;
       this.nomeLevantamento = nomeLevantamento;
       this.preco = preco;
       this.status = status;
    }
   
    public Integer getCodLevantamento() {
        return this.codLevantamento;
    }
    
    public void setCodLevantamento(Integer codLevantamento) {
        this.codLevantamento = codLevantamento;
    }
    public Parqueamento getParqueamento() {
        return this.parqueamento;
    }
    
    public void setParqueamento(Parqueamento parqueamento) {
        this.parqueamento = parqueamento;
    }
    public Calendar getData() {
        return this.data;
    }
    
    public void setData(Calendar data) {
        this.data = data;
    }
    public Time getHora() {
        return this.hora;
    }
    
    public void setHora(Time hora) {
        this.hora = hora;
    }
    public String getNomeLevantamento() {
        return this.nomeLevantamento;
    }
    
    public void setNomeLevantamento(String nomeLevantamento) {
        this.nomeLevantamento = nomeLevantamento;
    }
    public Float getPreco() {
        return this.preco;
    }
    
    public void setPreco(Float preco) {
        this.preco = preco;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


