package Model;
// Generated 02 Oct 2019 12:30:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Parqueamento generated by hbm2java
 */
public class Parqueamento implements Serializable {


     private Integer codParqueamento;
     private Cliente cliente;
     private Utilizador utilizador;
     private Vaga vaga;
     private Viatura viatura;
     private Calendar data;
     private Time hora;
     private String nomeAlternativo;
     private String nrBialternativo;
     private boolean status;

    public Parqueamento() {
    }

	
    public Parqueamento(Cliente cliente, Utilizador utilizador, Vaga vaga, Viatura viatura, Calendar data, Time hora, String nomeAlternativo, String nrBialternativo, boolean status) {
        this.cliente = cliente;
        this.utilizador = utilizador;
        this.vaga = vaga;
        this.viatura = viatura;
        this.data = data;
        this.hora = hora;
        this.nomeAlternativo = nomeAlternativo;
        this.nrBialternativo = nrBialternativo;
        this.status = status;
    }
    public Parqueamento(Cliente cliente, Utilizador utilizador, Vaga vaga, Viatura viatura, Calendar data, Time hora, String nomeAlternativo, String nrBialternativo, boolean status, Set levantamentos) {
       this.cliente = cliente;
       this.utilizador = utilizador;
       this.vaga = vaga;
       this.viatura = viatura;
       this.data = data;
       this.hora = hora;
       this.nomeAlternativo = nomeAlternativo;
       this.nrBialternativo = nrBialternativo;
       this.status = status;
    }
   
    public Integer getCodParqueamento() {
        return this.codParqueamento;
    }
    
    public void setCodParqueamento(Integer codParqueamento) {
        this.codParqueamento = codParqueamento;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Utilizador getUtilizador() {
        return this.utilizador;
    }
    
    public void setUtilizador(Utilizador utilizador) {
        this.utilizador = utilizador;
    }
    public Vaga getVaga() {
        return this.vaga;
    }
    
    public void setVaga(Vaga vaga) {
        this.vaga = vaga;
    }
    public Viatura getViatura() {
        return this.viatura;
    }
    
    public void setViatura(Viatura viatura) {
        this.viatura = viatura;
    }
    public Calendar getData() {
        return this.data;
    }
    
    public void setData(Calendar data) {
        this.data = data;
    }
    public Time getHora() {
        return this.hora;
    }
    
    public void setHora(Time hora) {
        this.hora = hora;
    }
    public String getNomeAlternativo() {
        return this.nomeAlternativo;
    }
    
    public void setNomeAlternativo(String nomeAlternativo) {
        this.nomeAlternativo = nomeAlternativo;
    }
    public String getNrBialternativo() {
        return this.nrBialternativo;
    }
    
    public void setNrBialternativo(String nrBialternativo) {
        this.nrBialternativo = nrBialternativo;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    

}


