package Model;
// Generated 10 Oct 2019 3:43:43 PM by Hibernate Tools 4.3.1



/**
 * Teste generated by hbm2java
 */
public class Teste  implements java.io.Serializable {


     private int id;
     private String nome;

    public Teste() {
    }

	
    public Teste(int id) {
        this.id = id;
    }
    public Teste(int id, String nome) {
       this.id = id;
       this.nome = nome;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


