package Model;
// Generated 02 Oct 2019 12:30:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Utilizador generated by hbm2java
 */
@Entity
@Table(name ="Utilizador")
public class Utilizador implements Serializable {
    
    
    @Id
    @Column(name = "idUtilizador")
    @GeneratedValue
     private Integer codUtilizador;
//     @ForeignKey(name = "numBI")
    
     @OneToMany
     private Funcionario funcionario;

     @Column(name = "nomeUtilizador", length = 30 , nullable = false , unique = true)
     private String nomeUtilizador;
     @Column(name = "password", length = 30 , nullable = false)
     private String password;
     @Column(name = "perfil", length = 20 , nullable = false)
     private String perfil;
     @Column(name = "estado", length = 10 , nullable = false)
     private boolean estado;
     @Column(name = "status", length = 10 , nullable = false)
     private boolean status;

    public Utilizador() {
    }

	
    public Utilizador(Funcionario funcionario, String nomeUtilizador, String password, String perfil, boolean estado, boolean status) {
        this.funcionario = funcionario;
        this.nomeUtilizador = nomeUtilizador;
        this.password = password;
        this.perfil = perfil;
        this.estado = estado;
        this.status = status;
    }
    public Utilizador(Funcionario funcionario, String nomeUtilizador, String password, String perfil, boolean estado, boolean status, Set parqueamentos) {
       this.funcionario = funcionario;
       this.nomeUtilizador = nomeUtilizador;
       this.password = password;
       this.perfil = perfil;
       this.estado = estado;
       this.status = status;
    }
   
    public Integer getCodUtilizador() {
        return this.codUtilizador;
    }
    
    public void setCodUtilizador(Integer codUtilizador) {
        this.codUtilizador = codUtilizador;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getNomeUtilizador() {
        return this.nomeUtilizador;
    }
    
    public void setNomeUtilizador(String nomeUtilizador) {
        this.nomeUtilizador = nomeUtilizador;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
   

}


