package Model;
// Generated 10 Oct 2019 3:43:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Utilizador generated by hbm2java
 */
public class Utilizador  implements java.io.Serializable {


     private Integer codUtilizador;
     private Funcionario funcionario;
     private String nomeUtilizador;
     private String password;
     private String perfil;
     private boolean estado;
     private boolean status;
     private Set parqueamentos = new HashSet(0);

    public Utilizador() {
    }

	
    public Utilizador(Funcionario funcionario, String nomeUtilizador, String password, String perfil, boolean estado, boolean status) {
        this.funcionario = funcionario;
        this.nomeUtilizador = nomeUtilizador;
        this.password = password;
        this.perfil = perfil;
        this.estado = estado;
        this.status = status;
    }
    public Utilizador(Funcionario funcionario, String nomeUtilizador, String password, String perfil, boolean estado, boolean status, Set parqueamentos) {
       this.funcionario = funcionario;
       this.nomeUtilizador = nomeUtilizador;
       this.password = password;
       this.perfil = perfil;
       this.estado = estado;
       this.status = status;
       this.parqueamentos = parqueamentos;
    }
   
    public Integer getCodUtilizador() {
        return this.codUtilizador;
    }
    
    public void setCodUtilizador(Integer codUtilizador) {
        this.codUtilizador = codUtilizador;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getNomeUtilizador() {
        return this.nomeUtilizador;
    }
    
    public void setNomeUtilizador(String nomeUtilizador) {
        this.nomeUtilizador = nomeUtilizador;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getParqueamentos() {
        return this.parqueamentos;
    }
    
    public void setParqueamentos(Set parqueamentos) {
        this.parqueamentos = parqueamentos;
    }




}


