package Model;
// Generated 02 Oct 2019 12:30:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vaga generated by hbm2java
 */
@Entity
@Table(name = "Vaga")
public class Vaga implements Serializable{

    @Id
    @GeneratedValue
    @Column(name= "idVaga")
     private Integer codVaga;
    @Column(name = "Categoria" ,length = 20 , nullable = false )
     private String categoria;
    @Column(name = "Descricao" ,length = 20 , nullable = false )
     private String descricao;
    @Column(name = "Valor" ,length = 20 , nullable = false )
     private float valor;
    @Column(name = "status" , nullable = false )
     private boolean status = true;

    public Vaga() {
    }

	
    public Vaga(String categoria, String descricao, float valor, boolean status) {
        this.categoria = categoria;
        this.descricao = descricao;
        this.valor = valor;
        this.status = status;
    }
    public Vaga(String categoria, String descricao, float valor, boolean status, Set parqueamentos) {
       this.categoria = categoria;
       this.descricao = descricao;
       this.valor = valor;
       this.status = status;
    }
   
    public Integer getCodVaga() {
        return this.codVaga;
    }
    
    public void setCodVaga(Integer codVaga) {
        this.codVaga = codVaga;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    
}


