package Model;
// Generated 10 Oct 2019 3:43:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Viatura generated by hbm2java
 */
public class Viatura  implements java.io.Serializable {


     private String matricula;
     private int codViatura;
     private String codMotor;
     private String codChassi;
     private String fabricante;
     private String modelo;
     private String tipo;
     private String estado;
     private boolean status;
     private Set parqueamentos = new HashSet(0);

    public Viatura() {
    }

	
    public Viatura(int codViatura, String codMotor, String codChassi, String fabricante, String modelo, String tipo, String estado, boolean status) {
        this.codViatura = codViatura;
        this.codMotor = codMotor;
        this.codChassi = codChassi;
        this.fabricante = fabricante;
        this.modelo = modelo;
        this.tipo = tipo;
        this.estado = estado;
        this.status = status;
    }
    public Viatura(int codViatura, String codMotor, String codChassi, String fabricante, String modelo, String tipo, String estado, boolean status, Set parqueamentos) {
       this.codViatura = codViatura;
       this.codMotor = codMotor;
       this.codChassi = codChassi;
       this.fabricante = fabricante;
       this.modelo = modelo;
       this.tipo = tipo;
       this.estado = estado;
       this.status = status;
       this.parqueamentos = parqueamentos;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public int getCodViatura() {
        return this.codViatura;
    }
    
    public void setCodViatura(int codViatura) {
        this.codViatura = codViatura;
    }
    public String getCodMotor() {
        return this.codMotor;
    }
    
    public void setCodMotor(String codMotor) {
        this.codMotor = codMotor;
    }
    public String getCodChassi() {
        return this.codChassi;
    }
    
    public void setCodChassi(String codChassi) {
        this.codChassi = codChassi;
    }
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getParqueamentos() {
        return this.parqueamentos;
    }
    
    public void setParqueamentos(Set parqueamentos) {
        this.parqueamentos = parqueamentos;
    }




}


