/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.placeholder.PlaceHolder;
import com.sun.xml.internal.ws.server.sei.ValueGetter;

/**
 *
 * @author Almerino Buce
 */
public class CadastroFuncionarios extends javax.swing.JPanel {

    /**
     * Creates new form Exemplar1
     */
    public void placeHolder() {
        PlaceHolder holder;
        holder = new PlaceHolder(tfMorada, "Introduza a Cidade, o Bairro e numero da Casa");
        
    }
    public CadastroFuncionarios() {
        initComponents();
         placeHolder();
        painelCadastroUtilizadores.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbnGrupoGenero = new javax.swing.ButtonGroup();
        painelCadastroUtilizadores = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jpTitulo = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jbPesquisar1 = new javax.swing.JButton();
        jlCargo = new javax.swing.JLabel();
        cbCargos = new javax.swing.JComboBox();
        jlGenero = new javax.swing.JLabel();
        tfBI = new javax.swing.JTextField();
        jlMorada = new javax.swing.JLabel();
        rbtnMasculino = new javax.swing.JRadioButton();
        rbtnFeminino = new javax.swing.JRadioButton();
        jlDepartamento = new javax.swing.JLabel();
        cbDepartamento = new javax.swing.JComboBox();
        tfMorada = new javax.swing.JTextField();
        jlBI1 = new javax.swing.JLabel();
        jlContacto = new javax.swing.JLabel();
        tfContacto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(940, 800));

        painelCadastroUtilizadores.setBackground(new java.awt.Color(255, 255, 255));
        painelCadastroUtilizadores.setMaximumSize(new java.awt.Dimension(1254, 798));
        painelCadastroUtilizadores.setName(""); // NOI18N
        painelCadastroUtilizadores.setPreferredSize(new java.awt.Dimension(1254, 798));

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        jlNome.setFont(new java.awt.Font("Bookman Old Style", 2, 16)); // NOI18N
        jlNome.setText("Nome");

        jpTitulo.setBackground(new java.awt.Color(153, 153, 255));

        jlTitulo.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jlTitulo.setText("Cadastro de Funcionario");

        jbPesquisar1.setText("Pesquisa");
        jbPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTituloLayout = new javax.swing.GroupLayout(jpTitulo);
        jpTitulo.setLayout(jpTituloLayout);
        jpTituloLayout.setHorizontalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addComponent(jbPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jpTituloLayout.setVerticalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGroup(jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlCargo.setFont(new java.awt.Font("Bookman Old Style", 2, 16)); // NOI18N
        jlCargo.setText("Cargo");

        cbCargos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o cargo", "Secretario", "Cozinheiro", "Manobrista", "Zelador" }));
        cbCargos.setNextFocusableComponent(this);
        cbCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCargosActionPerformed(evt);
            }
        });

        jlGenero.setFont(new java.awt.Font("Bookman Old Style", 2, 16)); // NOI18N
        jlGenero.setText("Genero");

        tfBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBIActionPerformed(evt);
            }
        });

        jlMorada.setFont(new java.awt.Font("Bookman Old Style", 2, 16)); // NOI18N
        jlMorada.setText("Morada");

        tbnGrupoGenero.add(rbtnMasculino);
        rbtnMasculino.setText("Maculino");
        rbtnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMasculinoActionPerformed(evt);
            }
        });

        tbnGrupoGenero.add(rbtnFeminino);
        rbtnFeminino.setText("Feminino");
        rbtnFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemininoActionPerformed(evt);
            }
        });

        jlDepartamento.setFont(new java.awt.Font("Bookman Old Style", 2, 16)); // NOI18N
        jlDepartamento.setText("Departamento");

        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o Departamento", "Administracao", "Cozinha", "Seguranca", "outros" }));
        cbDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartamentoActionPerformed(evt);
            }
        });

        tfMorada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMoradaActionPerformed(evt);
            }
        });

        jlBI1.setFont(new java.awt.Font("Bookman Old Style", 2, 16)); // NOI18N
        jlBI1.setText("N. BI");

        jlContacto.setFont(new java.awt.Font("Bookman Old Style", 2, 16)); // NOI18N
        jlContacto.setText("Contacto");

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 2, 16)); // NOI18N
        jLabel1.setText("Email");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover");

        javax.swing.GroupLayout painelCadastroUtilizadoresLayout = new javax.swing.GroupLayout(painelCadastroUtilizadores);
        painelCadastroUtilizadores.setLayout(painelCadastroUtilizadoresLayout);
        painelCadastroUtilizadoresLayout.setHorizontalGroup(
            painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(271, 271, 271)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                                .addComponent(rbtnMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174))
                            .addComponent(tfMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField1)
                        .addComponent(jlNome)
                        .addComponent(tfNome)
                        .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                            .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfBI, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlBI1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlGenero))
                            .addGap(125, 125, 125)
                            .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlCargo)
                                .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfContacto)
                                    .addComponent(cbCargos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, 0, 346, Short.MAX_VALUE)
                                    .addComponent(jlDepartamento))))
                        .addComponent(jLabel1))
                    .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                        .addComponent(jlMorada)
                        .addGap(418, 418, 418)
                        .addComponent(jlContacto)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addComponent(jpTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelCadastroUtilizadoresLayout.setVerticalGroup(
            painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                .addComponent(jpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBI1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                        .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnMasculino)
                            .addComponent(cbCargos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnFeminino))
                        .addGap(49, 49, 49)
                        .addComponent(jlContacto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                        .addComponent(jlMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1))
                    .addGroup(painelCadastroUtilizadoresLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(painelCadastroUtilizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastroUtilizadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelCadastroUtilizadores, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBIActionPerformed

    private void rbtnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMasculinoActionPerformed

    private void rbtnFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemininoActionPerformed

    private void cbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepartamentoActionPerformed

    private void tfMoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMoradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMoradaActionPerformed

    private void cbCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCargosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCargosActionPerformed

    private void jbPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPesquisar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCargos;
    private javax.swing.JComboBox cbDepartamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbPesquisar1;
    private javax.swing.JLabel jlBI1;
    private javax.swing.JLabel jlCargo;
    private javax.swing.JLabel jlContacto;
    private javax.swing.JLabel jlDepartamento;
    private javax.swing.JLabel jlGenero;
    private javax.swing.JLabel jlMorada;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel painelCadastroUtilizadores;
    private javax.swing.JRadioButton rbtnFeminino;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.ButtonGroup tbnGrupoGenero;
    private javax.swing.JTextField tfBI;
    private javax.swing.JTextField tfContacto;
    private javax.swing.JTextField tfMorada;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
