/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GeralDAO;
import static Controller.GeralDAO.listarFuncionarios;
import static Controller.GeralDAO.listarViaturas;
import static Controller.GeralDAO.pesquisarViaturas;
import Model.Funcionarios;
import Model.Viatura;
import Model.Viaturas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static metodos.StringToDate.converterData;
import static metodos.StringToDate.converterString;
import metodos.Tabela;

/**
 *
 * @author Almerino Buce
 */
public class FormularioViatura extends javax.swing.JPanel {

    int cod;
    String estado;

    Viaturas viaturas = new Viaturas();
    GeralDAO<Viaturas> dao = new GeralDAO<>();
    Tabela tabela = new Tabela();

    public void desabilitarCampos() {
        textFieldModelo.setEnabled(false);
        TextFieldFabricante.setEnabled(false);
        comboBoxTipo.setEnabled(false);
    }

    public void HabilitarCampos() {
        textFieldModelo.setEnabled(true);
        TextFieldFabricante.setEnabled(true);
        comboBoxTipo.setEnabled(true);
    }

    public void limparCampos() {
        textFieldMatricula.setText("");
        textFieldModelo.setText("");
        TextFieldFabricante.setText("");
        TextFieldCor.setText("");
        TextFieldCodMotor.setText("");
        comboBoxTipo.setSelectedItem("Selecione o tipo");
        TextFieldNumChassis.setText("");
        buttonGroupEstado.clearSelection();
    }

    public void listar() {
        for (Viaturas v : listarViaturas()) {
            if (v.getStatus().equalsIgnoreCase("True")) {
                DefaultTableModel model = (DefaultTableModel) TableViatura.getModel();
                model.addRow(new Object[]{v.getCodViatura(), v.getMatricula(), v.getCodMotor(), v.getCodChassi(), v.getFabricante(), v.getModelo(), v.getTipo(), v.getCor(), v.getEstado()});
            }
        }
    }

    public FormularioViatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelMatricula = new javax.swing.JLabel();
        textFieldMatricula = new javax.swing.JTextField();
        labelModelo = new javax.swing.JLabel();
        textFieldModelo = new javax.swing.JTextField();
        labelTipoViatura = new javax.swing.JLabel();
        labelFabricante = new javax.swing.JLabel();
        TextFieldCor = new javax.swing.JTextField();
        labelNumChassis = new javax.swing.JLabel();
        TextFieldNumChassis = new javax.swing.JTextField();
        ButtonSalvar = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonList = new javax.swing.JButton();
        TabbedPaneViatura = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableViatura = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ButtonSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelCodigoMotor = new javax.swing.JLabel();
        TextFieldCodMotor = new javax.swing.JTextField();
        labelCor = new javax.swing.JLabel();
        TextFieldFabricante = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox();
        radioButtonOperacional = new javax.swing.JRadioButton();
        radioButtonAvariado = new javax.swing.JRadioButton();
        ButtonImprimir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(940, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1254, 798));

        labelMatricula.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelMatricula.setText("Matricula");

        textFieldMatricula.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        labelModelo.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelModelo.setText("Modelo");

        textFieldModelo.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        textFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldModeloActionPerformed(evt);
            }
        });

        labelTipoViatura.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelTipoViatura.setText("Tipo");

        labelFabricante.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelFabricante.setText("Fabricante");

        TextFieldCor.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        labelNumChassis.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelNumChassis.setText("Codigo de chassi");

        TextFieldNumChassis.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        TextFieldNumChassis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNumChassisActionPerformed(evt);
            }
        });

        ButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add1.png"))); // NOI18N
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        ButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Update.png"))); // NOI18N
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        ButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonList.setBackground(new java.awt.Color(255, 255, 255));
        ButtonList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/List.png"))); // NOI18N
        ButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListActionPerformed(evt);
            }
        });

        TableViatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Matricula", "Codigo do motor", "Codigo de chassi", "Fabricante", "Modelo", "Tipo", "Cor", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableViatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableViaturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableViatura);

        TabbedPaneViatura.addTab("Tabela de Viaturas", jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(129, 190, 234));

        ButtonSearch.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel3.setText("Viatura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelCodigoMotor.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelCodigoMotor.setText("Codigo do motor");

        TextFieldCodMotor.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        TextFieldCodMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCodMotorActionPerformed(evt);
            }
        });

        labelCor.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelCor.setText("Cor");

        TextFieldFabricante.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        labelEstado.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelEstado.setText("Estado ");

        comboBoxTipo.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o tipo", "Sedan", "Hatchback", "SUV", "PickUp", "Camiao", "Camioneta", "Van", "Mini-Van", "Autocarro", "Mini-Autocarro", "Outros", " " }));

        buttonGroupEstado.add(radioButtonOperacional);
        radioButtonOperacional.setText("Operacional");
        radioButtonOperacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonOperacionalActionPerformed(evt);
            }
        });

        buttonGroupEstado.add(radioButtonAvariado);
        radioButtonAvariado.setText("Avariado");
        radioButtonAvariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAvariadoActionPerformed(evt);
            }
        });

        ButtonImprimir.setBackground(new java.awt.Color(255, 255, 255));
        ButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Print.png"))); // NOI18N
        ButtonImprimir.setToolTipText("Imprimir");
        ButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TabbedPaneViatura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodigoMotor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldCodMotor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFabricante)
                                    .addComponent(labelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(TextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextFieldNumChassis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                                            .addComponent(labelNumChassis, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(radioButtonOperacional)
                                                .addGap(30, 30, 30)
                                                .addComponent(radioButtonAvariado))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelTipoViatura, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoViatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumChassis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNumChassis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButtonOperacional)
                            .addComponent(radioButtonAvariado))))
                .addGap(12, 12, 12)
                .addComponent(labelCodigoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldCodMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TabbedPaneViatura, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldModeloActionPerformed

    private void TextFieldNumChassisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNumChassisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNumChassisActionPerformed

    private void ButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListActionPerformed
        HabilitarCampos();
        tabela.limpaJtable(TableViatura);
        listar();
        limparCampos();
    }//GEN-LAST:event_ButtonListActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        HabilitarCampos();
        int opcao = (JOptionPane.showConfirmDialog(this, "Tem Certeza de que pretende Apagar o"
                + " Registo?", "Apagando Registo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE));
        if (opcao == 0) {
            viaturas.setCodViatura(cod);
            viaturas.setMatricula(textFieldMatricula.getText());
            viaturas.setModelo(textFieldModelo.getText());
            viaturas.setFabricante(TextFieldFabricante.getText());
            viaturas.setCor(TextFieldCor.getText());
            viaturas.setCodMotor(TextFieldCodMotor.getText());
            viaturas.setTipo(comboBoxTipo.getSelectedItem().toString());
            viaturas.setCodChassi(TextFieldNumChassis.getText());
            viaturas.setEstado(estado);
            viaturas.setStatus("False");
            dao.editar(viaturas);
            tabela.limpaJtable(TableViatura);
            listar();
        }
        limparCampos();
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void TextFieldCodMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodMotorActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        HabilitarCampos();
        viaturas.setMatricula(textFieldMatricula.getText());
        viaturas.setModelo(textFieldModelo.getText());
        viaturas.setFabricante(TextFieldFabricante.getText());
        viaturas.setCor(TextFieldCor.getText());
        viaturas.setCodMotor(TextFieldCodMotor.getText());
        viaturas.setTipo(comboBoxTipo.getSelectedItem().toString());
        viaturas.setCodChassi(TextFieldNumChassis.getText());
        viaturas.setEstado(estado);
        viaturas.setStatus("True");
        dao.salvar(viaturas);
        tabela.limpaJtable(TableViatura);
        listar();
        limparCampos();
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void radioButtonOperacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonOperacionalActionPerformed
        estado = "Operacional";
    }//GEN-LAST:event_radioButtonOperacionalActionPerformed

    private void radioButtonAvariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAvariadoActionPerformed
        estado = "Avariado";
    }//GEN-LAST:event_radioButtonAvariadoActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        HabilitarCampos();
        viaturas.setCodViatura(cod);
        viaturas.setMatricula(textFieldMatricula.getText());
        viaturas.setModelo(textFieldModelo.getText());
        viaturas.setFabricante(TextFieldFabricante.getText());
        viaturas.setCor(TextFieldCor.getText());
        viaturas.setCodMotor(TextFieldCodMotor.getText());
        viaturas.setTipo(comboBoxTipo.getSelectedItem().toString());
        viaturas.setCodChassi(TextFieldNumChassis.getText());
        viaturas.setEstado(estado);
        viaturas.setStatus("True");
        dao.editar(viaturas);
        tabela.limpaJtable(TableViatura);
        listar();
        limparCampos();
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void TableViaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableViaturaMouseClicked
        buttonGroupEstado.clearSelection();
        textFieldMatricula.setText((String) TableViatura.getValueAt(TableViatura.getSelectedRow(), 1));
        textFieldModelo.setText((String) TableViatura.getValueAt(TableViatura.getSelectedRow(), 5));
        TextFieldFabricante.setText((String) TableViatura.getValueAt(TableViatura.getSelectedRow(), 4));
        TextFieldCor.setText((String) TableViatura.getValueAt(TableViatura.getSelectedRow(), 7));
        TextFieldCodMotor.setText((String) TableViatura.getValueAt(TableViatura.getSelectedRow(), 2));
        comboBoxTipo.setSelectedItem((String) TableViatura.getValueAt(TableViatura.getSelectedRow(), 6));
        TextFieldNumChassis.setText((String) TableViatura.getValueAt(TableViatura.getSelectedRow(), 3));
        String tipo = ((String) TableViatura.getValueAt(TableViatura.getSelectedRow(), 8));
        if (tipo.equalsIgnoreCase("Operacional")) {
            radioButtonOperacional.setSelected(true);
            estado = "Operacional";
        } else if (tipo.equalsIgnoreCase("Avariado")) {
            radioButtonAvariado.setSelected(true);
            estado = "Avariado";
        }
        cod = Integer.parseInt(String.valueOf(TableViatura.getValueAt(TableViatura.getSelectedRow(), 0)));
        desabilitarCampos();

    }//GEN-LAST:event_TableViaturaMouseClicked

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        tabela.limpaJtable(TableViatura);
        for (Viaturas v : pesquisarViaturas(textFieldMatricula.getText())) {
            if (v.getStatus().equalsIgnoreCase("True")) {
                DefaultTableModel model = (DefaultTableModel) TableViatura.getModel();
                model.addRow(new Object[]{v.getCodViatura(), v.getMatricula(), v.getCodMotor(), v.getCodChassi(), v.getFabricante(), v.getModelo(), v.getTipo(), v.getCor(), v.getEstado()});
            }
        }
        limparCampos();
    }//GEN-LAST:event_ButtonSearchActionPerformed

    private void ButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonImprimir;
    private javax.swing.JButton ButtonList;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JTabbedPane TabbedPaneViatura;
    private javax.swing.JTable TableViatura;
    private javax.swing.JTextField TextFieldCodMotor;
    private javax.swing.JTextField TextFieldCor;
    private javax.swing.JTextField TextFieldFabricante;
    private javax.swing.JTextField TextFieldNumChassis;
    private javax.swing.ButtonGroup buttonGroupEstado;
    private javax.swing.JComboBox comboBoxTipo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCodigoMotor;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFabricante;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelNumChassis;
    private javax.swing.JLabel labelTipoViatura;
    private javax.swing.JRadioButton radioButtonAvariado;
    private javax.swing.JRadioButton radioButtonOperacional;
    private javax.swing.JTextField textFieldMatricula;
    private javax.swing.JTextField textFieldModelo;
    // End of variables declaration//GEN-END:variables
}
