/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GeralDAO;
import static Controller.GeralDAO.listarClientes;
import static Controller.GeralDAO.listarParqueamentos;
import static Controller.GeralDAO.listarVagas;
import static Controller.GeralDAO.listarViaturas;
import Controller.OutrasOperacoesDao;
import Model.Clientes;
import Model.Parqueamentos;
import Model.Vagas;
import Model.Viaturas;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static metodos.StringToDate.converterData;
import static metodos.StringToDate.converterString;
import metodos.Tabela;

/**
 *
 * @author Almerino Buce
 */
public class FormularioParqueamento extends javax.swing.JPanel {
    
    String categoria;
    
    public void desabilitarCampos() {
        comboBoxNumBi.setEnabled(false);
        comboBoxMatricula.setEnabled(false);
        radioButtonContrato.setEnabled(false);
        radioButtonSemContrato.setEnabled(false);
        ComboBoxVaga.setEnabled(false);
    }
    
    public void HabilitarCampos() {
        comboBoxNumBi.setEnabled(true);
        comboBoxMatricula.setEnabled(true);
        radioButtonContrato.setEnabled(true);
        radioButtonSemContrato.setEnabled(true);
        ComboBoxVaga.setEnabled(true);
    }
    
    public void limparCampos() {
        textFieldNumBiAlt.setText("");
        textFieldNomeAlt.setText("");
        buttonGroupTipoParqueamento.clearSelection();
        comboBoxNumBi.setSelectedItem("");
        comboBoxMatricula.setSelectedItem("");
        ComboBoxVaga.setSelectedItem("");
    }
    
    public void listar() {
        for (Parqueamentos p : listarParqueamentos()) {
            if (p.getStatus().equalsIgnoreCase("True")) {
                DefaultTableModel model = (DefaultTableModel) TableParqueamento.getModel();
                model.addRow(new Object[]{p.getCodParqueamento(), p.getTipoParqueamento(), p.getNrBI(), p.getMatricula(), p.getNrBIAlternativo(), p.getNomeAlternativo(), p.getVagaDescricao(), p.getEstado(), p.getDataP(), p.getHoraP()});
            }
        }
    }
    
    public void getCliente(JComboBox comboBox, String contrato) {
        int i = 0;
        comboBox.removeAllItems();
        comboBox.addItem("");
        for (Clientes c : listarClientes()) {
            if (c.getContrato().equalsIgnoreCase(contrato) && c.getStatus().equalsIgnoreCase("True")) {
                for (Parqueamentos p : listarParqueamentos()) {
                    if (c.getNrBI().equalsIgnoreCase(p.getNrBI()) && p.getEstado().equalsIgnoreCase("Inactivo") && p.getStatus().equalsIgnoreCase("True")) {
                        i = i + 1;
                    }
                }
                if (i != 0) {
                    comboBox.addItem(c.getNrBI());
                }
                i = 0;
            }
        }
    }
    
    public void buscarCategoria(String matricula) {
        for (Viaturas v : listarViaturas()) {
            if (v.getMatricula().equalsIgnoreCase(matricula)) {
                categoria = v.getTipo();
            }
        }
    }

//    public void getMatricula(JComboBox comboBox) {
//        comboBox.addItem("");
//        for (Viaturas v : listarViaturas()) {
//            comboBox.addItem(v.getMatricula());
//        }
//    }
    public void getVaga(JComboBox comboBox) {
        comboBox.removeAllItems();
        comboBox.addItem("");
        for (Vagas v : listarVagas()) {
            if (v.getStatus().equals("True")) {
                comboBox.addItem(v.getDescricao());
            }
        }
    }
    Parqueamentos parqueamentos = new Parqueamentos();
    GeralDAO<Parqueamentos> gd = new GeralDAO<>();
    String tipoParqueamento;
    Tabela tabela = new Tabela();
    OutrasOperacoesDao o = new OutrasOperacoesDao();
    int cod;

    /**
     * Creates new form Exemplar1
     */
    public FormularioParqueamento() {
        initComponents();
        comboBoxNumBi.addItem("");
        o.listarViaturasParaParqueamento(comboBoxMatricula);
        getVaga(ComboBoxVaga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoParqueamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelTipParqueamento = new javax.swing.JLabel();
        labelNumBI = new javax.swing.JLabel();
        labelMatricula = new javax.swing.JLabel();
        labelVaga = new javax.swing.JLabel();
        ComboBoxVaga = new javax.swing.JComboBox<>();
        ButtonSalvar = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonList = new javax.swing.JButton();
        TabbedPaneParqueamento = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableParqueamento = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ButtonSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboBoxNumBi = new javax.swing.JComboBox<>();
        radioButtonContrato = new javax.swing.JRadioButton();
        radioButtonSemContrato = new javax.swing.JRadioButton();
        comboBoxMatricula = new javax.swing.JComboBox<>();
        labelBiAlternativo = new javax.swing.JLabel();
        textFieldNumBiAlt = new javax.swing.JTextField();
        labelNomeAlternativo = new javax.swing.JLabel();
        textFieldNomeAlt = new javax.swing.JTextField();
        ButtonImprimir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(940, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1254, 798));

        labelTipParqueamento.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelTipParqueamento.setText("Tipo de parqueamento");

        labelNumBI.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelNumBI.setText("Numero do BI");

        labelMatricula.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelMatricula.setText("Matricula");

        labelVaga.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelVaga.setText("Vaga a ocupar");

        ButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add1.png"))); // NOI18N
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        ButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Update.png"))); // NOI18N
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        ButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonList.setBackground(new java.awt.Color(255, 255, 255));
        ButtonList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/List.png"))); // NOI18N
        ButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListActionPerformed(evt);
            }
        });

        TableParqueamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tipo", "BI", "Matricula", "BI Alternativo", "Nome alternativo", "Vaga", "Estado", "Data", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableParqueamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableParqueamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableParqueamento);

        TabbedPaneParqueamento.addTab("Tabela parqueamentos", jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(129, 190, 234));

        ButtonSearch.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel3.setText("Parqueamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 621, Short.MAX_VALUE)
                .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboBoxNumBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNumBiActionPerformed(evt);
            }
        });

        buttonGroupTipoParqueamento.add(radioButtonContrato);
        radioButtonContrato.setText("Contrato");
        radioButtonContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonContratoActionPerformed(evt);
            }
        });

        buttonGroupTipoParqueamento.add(radioButtonSemContrato);
        radioButtonSemContrato.setText("Sem contrato");
        radioButtonSemContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSemContratoActionPerformed(evt);
            }
        });

        comboBoxMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMatriculaActionPerformed(evt);
            }
        });

        labelBiAlternativo.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelBiAlternativo.setText("Numero de BI Alternativo");

        labelNomeAlternativo.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelNomeAlternativo.setText("Nome Alternativo");

        ButtonImprimir.setBackground(new java.awt.Color(255, 255, 255));
        ButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Print.png"))); // NOI18N
        ButtonImprimir.setToolTipText("Imprimir");
        ButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TabbedPaneParqueamento, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(radioButtonContrato)
                                    .addGap(18, 18, 18)
                                    .addComponent(radioButtonSemContrato))
                                .addComponent(labelVaga)
                                .addComponent(labelTipParqueamento, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comboBoxNumBi, 0, 352, Short.MAX_VALUE)
                                        .addComponent(labelNumBI, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelBiAlternativo)
                                        .addComponent(textFieldNumBiAlt))
                                    .addGap(56, 56, 56)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboBoxMatricula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelNomeAlternativo))
                                            .addGap(0, 221, Short.MAX_VALUE))
                                        .addComponent(textFieldNomeAlt)))
                                .addComponent(ComboBoxVaga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(labelTipParqueamento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonContrato)
                    .addComponent(radioButtonSemContrato))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumBI, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxNumBi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelBiAlternativo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNumBiAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNomeAlternativo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNomeAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(labelVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(TabbedPaneParqueamento, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListActionPerformed
        HabilitarCampos();
        tabela.limpaJtable(TableParqueamento);
        listar();
        limparCampos();

    }//GEN-LAST:event_ButtonListActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        HabilitarCampos();
        int opcao = (JOptionPane.showConfirmDialog(this, "Tem Certeza de que pretende Apagar o"
                + " Registo?", "Apagando Registo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE));
        if (opcao == 0) {
            o.apagarParqueamento(cod);
            tabela.limpaJtable(TableParqueamento);
            listar();
        }
        limparCampos();
        o.listarViaturasParaParqueamento(comboBoxMatricula);
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void comboBoxNumBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNumBiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxNumBiActionPerformed

    private void radioButtonContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonContratoActionPerformed
        tipoParqueamento = "Activo";
        getCliente(comboBoxNumBi, tipoParqueamento);
        o.listarClientesContratoParaParqueamento(comboBoxNumBi);
//        o.listarClientesContratoParaParqueamentoI(comboBoxNumBi);
    }//GEN-LAST:event_radioButtonContratoActionPerformed

    private void radioButtonSemContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSemContratoActionPerformed
        tipoParqueamento = "Inactivo";
//        getCliente(comboBoxNumBi, tipoParqueamento);
        o.listarClientesSemContratoParaParqueamento(comboBoxNumBi);
        o.listarClientesSemContratoParaParqueamentoI(comboBoxNumBi);
    }//GEN-LAST:event_radioButtonSemContratoActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        HabilitarCampos();
        parqueamentos.setTipoParqueamento(tipoParqueamento);
        parqueamentos.setMatricula(comboBoxMatricula.getSelectedItem().toString());
        parqueamentos.setNrBI(comboBoxNumBi.getSelectedItem().toString());
        parqueamentos.setNrBIAlternativo(textFieldNumBiAlt.getText());
        parqueamentos.setNomeAlternativo(textFieldNomeAlt.getText());
        parqueamentos.setVagaDescricao(ComboBoxVaga.getSelectedItem().toString());
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date hoje = new Date();
        parqueamentos.setDataP((df.format(hoje)));
        SimpleDateFormat dfa = new SimpleDateFormat("HH:mm:ss");
        Date agora = new Date();
        parqueamentos.setHoraP(dfa.format(agora));
        parqueamentos.setEstado("Activo");
        parqueamentos.setStatus("True");
        gd.salvar(parqueamentos);
        o.actualizarEstadoVaga(ComboBoxVaga.getSelectedItem().toString());
        tabela.limpaJtable(TableParqueamento);
        listar();
        limparCampos();
        o.listarViaturasParaParqueamento(comboBoxMatricula);

    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void comboBoxMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMatriculaActionPerformed
        buscarCategoria(comboBoxMatricula.getSelectedItem().toString());
        o.listarVagasParaParqueamento(ComboBoxVaga, categoria);
    }//GEN-LAST:event_comboBoxMatriculaActionPerformed

    private void ButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonImprimirActionPerformed
////        o.imprimir("G:\\UEM\\NÍVEL II\\SEMESTRE II\\POO\\Trabe_Semestral_POO\\relatorios\\RelatorioParqueamento.jasper");
    }//GEN-LAST:event_ButtonImprimirActionPerformed

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        HabilitarCampos();
        o.actualizarParqueamento(textFieldNumBiAlt.getText(), textFieldNomeAlt.getText(), cod);
        tabela.limpaJtable(TableParqueamento);
        listar();
        limparCampos();

    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void TableParqueamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableParqueamentoMouseClicked
        buttonGroupTipoParqueamento.clearSelection();
        comboBoxNumBi.setSelectedItem((String) TableParqueamento.getValueAt(TableParqueamento.getSelectedRow(), 2));
        comboBoxMatricula.setSelectedItem((String) TableParqueamento.getValueAt(TableParqueamento.getSelectedRow(), 3));
        textFieldNumBiAlt.setText((String) TableParqueamento.getValueAt(TableParqueamento.getSelectedRow(), 4));
        textFieldNomeAlt.setText((String) TableParqueamento.getValueAt(TableParqueamento.getSelectedRow(), 5));
        ComboBoxVaga.setSelectedItem((String) TableParqueamento.getValueAt(TableParqueamento.getSelectedRow(), 6));
        String tipo = ((String) TableParqueamento.getValueAt(TableParqueamento.getSelectedRow(), 7));
        if (tipo.equalsIgnoreCase("Activo")) {
            radioButtonContrato.setSelected(true);
            tipoParqueamento = "Activo";
        } else if (tipo.equalsIgnoreCase("Inactivo")) {
            radioButtonSemContrato.setSelected(true);
            tipoParqueamento = "Inactivo";
        }
        cod = Integer.parseInt(String.valueOf(TableParqueamento.getValueAt(TableParqueamento.getSelectedRow(), 0)));
        desabilitarCampos();

    }//GEN-LAST:event_TableParqueamentoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonImprimir;
    private javax.swing.JButton ButtonList;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JComboBox<String> ComboBoxVaga;
    private javax.swing.JTabbedPane TabbedPaneParqueamento;
    private javax.swing.JTable TableParqueamento;
    private javax.swing.ButtonGroup buttonGroupTipoParqueamento;
    private javax.swing.JComboBox<String> comboBoxMatricula;
    private javax.swing.JComboBox<String> comboBoxNumBi;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBiAlternativo;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelNomeAlternativo;
    private javax.swing.JLabel labelNumBI;
    private javax.swing.JLabel labelTipParqueamento;
    private javax.swing.JLabel labelVaga;
    private javax.swing.JRadioButton radioButtonContrato;
    private javax.swing.JRadioButton radioButtonSemContrato;
    private javax.swing.JTextField textFieldNomeAlt;
    private javax.swing.JTextField textFieldNumBiAlt;
    // End of variables declaration//GEN-END:variables
}
