/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GeralDAO;
import static Controller.GeralDAO.listarClientes;
import static Controller.GeralDAO.listarFuncionarios;
import static Controller.GeralDAO.listarUtilizadores;
import static Controller.GeralDAO.pesquisarClientes;
import static Controller.GeralDAO.pesquisarFuncionarios;
import Model.Cliente;
import Model.Clientes;
import Model.Funcionarios;
import Model.Utilizadores;
import com.placeholder.PlaceHolder;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static metodos.StringToDate.converterData;
import static metodos.StringToDate.converterLocal;
import static metodos.StringToDate.converterString;
import metodos.Tabela;
import org.hibernate.cfg.annotations.reflection.XMLContext;

/**
 *
 * @author Almerino Buce
 */
public class FormularioCliente extends javax.swing.JPanel {

    int cod;
    String genero;
    String contrato;
    Clientes clientes = new Clientes();
    GeralDAO<Clientes> dao = new GeralDAO<>();
    Tabela tabela = new Tabela();

    public void listar() {
        for (Clientes c : listarClientes()) {
            if (c.getStatus().equalsIgnoreCase("True")) {
                DefaultTableModel model = (DefaultTableModel) TableCliente.getModel();
                model.addRow(new Object[]{c.getCodCliente(), c.getNrBI(), c.getNomeCompleto(), c.getSexo(), c.getDataNascimento(), c.getMorada(), c.getContacto(), c.getEmail(), c.getContrato()});
            }
        }
    }

    public void desabilitarCampos() {
        textFieldNome.setEnabled(false);
        textFiledNumBi.setEnabled(false);
        RadioButtonSexoFem.setEnabled(false);
        RadioButtonSexoMasc.setEnabled(false);
        dateChooserDataNascimento.setEnabled(false);
    }

    public void HabilitarCampos() {
        textFieldNome.setEnabled(true);
        textFiledNumBi.setEnabled(true);
        RadioButtonSexoFem.setEnabled(true);
        RadioButtonSexoMasc.setEnabled(true);
        dateChooserDataNascimento.setEnabled(true);
    }

    public void limparCampos() {
        textFieldNome.setText("");
        textFieldContacto.setText("");
        TextFieldMorada.setText("");
        buttonGroupGeneroCliente.clearSelection();
        textFieldEmail.setText("");
        textFiledNumBi.setText("");
        buttonGroupContrato.clearSelection();
        dateChooserDataNascimento.setDate(converterString(""));
    }

    public FormularioCliente() {
        initComponents();
        //PlaceHolder holder = new PlaceHolder(formattedTextDataNasc, "ano/mes/dia");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGeneroCliente = new javax.swing.ButtonGroup();
        buttonGroupContrato = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelContacto = new javax.swing.JLabel();
        textFieldContacto = new javax.swing.JTextField();
        labelNumBi = new javax.swing.JLabel();
        textFiledNumBi = new javax.swing.JTextField();
        labelMorada = new javax.swing.JLabel();
        TextFieldMorada = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        RadioButtonSexoFem = new javax.swing.JRadioButton();
        RadioButtonSexoMasc = new javax.swing.JRadioButton();
        labelContrato = new javax.swing.JLabel();
        ButtonSalvar = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonList = new javax.swing.JButton();
        TabbedPaneCliente = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ButtonSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelDataNac = new javax.swing.JLabel();
        RadioButtonContrato = new javax.swing.JRadioButton();
        RadioButtonSemContrato = new javax.swing.JRadioButton();
        ButtonImprimir = new javax.swing.JButton();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        dateChooserDataNascimento = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(940, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1254, 798));

        labelNome.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelNome.setText("Nome");

        textFieldNome.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        textFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelContacto.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelContacto.setText("Contacto");

        textFieldContacto.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        textFieldContacto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContactoActionPerformed(evt);
            }
        });

        labelNumBi.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelNumBi.setText("Numero de BI");

        textFiledNumBi.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        textFiledNumBi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFiledNumBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFiledNumBiActionPerformed(evt);
            }
        });

        labelMorada.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelMorada.setText("Morada");

        TextFieldMorada.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        TextFieldMorada.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelGenero.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelGenero.setText("Genero");

        buttonGroupGeneroCliente.add(RadioButtonSexoFem);
        RadioButtonSexoFem.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        RadioButtonSexoFem.setText("Feminino");
        RadioButtonSexoFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSexoFemActionPerformed(evt);
            }
        });

        buttonGroupGeneroCliente.add(RadioButtonSexoMasc);
        RadioButtonSexoMasc.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        RadioButtonSexoMasc.setText("Masculino");
        RadioButtonSexoMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSexoMascActionPerformed(evt);
            }
        });

        labelContrato.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelContrato.setText("Contrato");

        ButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add1.png"))); // NOI18N
        ButtonSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        ButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Update.png"))); // NOI18N
        ButtonUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        ButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        ButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonList.setBackground(new java.awt.Color(255, 255, 255));
        ButtonList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/List.png"))); // NOI18N
        ButtonList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListActionPerformed(evt);
            }
        });

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "BI", "Nome", "Genero", "Data de nascimento", "Morada", "Contacto", "Email", "Contrato"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableCliente);

        TabbedPaneCliente.addTab("Tabela de Clientes", jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(129, 190, 234));

        ButtonSearch.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel3.setText("Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelDataNac.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelDataNac.setText("Data de nascimento");

        buttonGroupContrato.add(RadioButtonContrato);
        RadioButtonContrato.setText("Contrato");
        RadioButtonContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonContratoActionPerformed(evt);
            }
        });

        buttonGroupContrato.add(RadioButtonSemContrato);
        RadioButtonSemContrato.setText("Sem contrato");
        RadioButtonSemContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonSemContratoActionPerformed(evt);
            }
        });

        ButtonImprimir.setBackground(new java.awt.Color(255, 255, 255));
        ButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Print.png"))); // NOI18N
        ButtonImprimir.setToolTipText("Imprimir");
        ButtonImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonImprimirActionPerformed(evt);
            }
        });

        labelEmail.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelEmail.setText("Email");

        textFieldEmail.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        textFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dateChooserDataNascimento.setDateFormatString("dd-MM-yyyy");
        dateChooserDataNascimento.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(801, 801, 801))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(801, 801, 801))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldNome)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelMorada)
                                        .addComponent(TextFieldMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(RadioButtonSexoFem)
                                            .addGap(18, 18, 18)
                                            .addComponent(RadioButtonSexoMasc))
                                        .addComponent(labelContacto))
                                    .addGap(56, 56, 56)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFiledNumBi)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelNumBi)
                                                .addComponent(labelContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelDataNac)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(RadioButtonContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(RadioButtonSemContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(dateChooserDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(TabbedPaneCliente)
                                .addComponent(textFieldEmail)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(126, 126, 126)))
                            .addGap(80, 80, 80)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumBi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFiledNumBi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(labelMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioButtonSemContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDataNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioButtonSexoFem)
                        .addComponent(RadioButtonSexoMasc))
                    .addComponent(dateChooserDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TabbedPaneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void textFiledNumBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFiledNumBiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFiledNumBiActionPerformed

    private void textFieldContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldContactoActionPerformed

    private void ButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListActionPerformed
        HabilitarCampos();
        tabela.limpaJtable(TableCliente);
        listar();
        limparCampos();
    }//GEN-LAST:event_ButtonListActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        HabilitarCampos();
        int opcao = (JOptionPane.showConfirmDialog(this, "Tem Certeza de que pretende Apagar o"
                + " Registo?", "Apagando Registo", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE));
        if (opcao == 0) {
            clientes.setCodCliente(cod);
            clientes.setNomeCompleto(textFieldNome.getText());
            clientes.setContacto(textFieldContacto.getText());
            clientes.setMorada(TextFieldMorada.getText());
            clientes.setSexo(genero);
            clientes.setNrBI(textFiledNumBi.getText());
            clientes.setContrato(contrato);
            clientes.setDataNascimento(converterData(dateChooserDataNascimento.getDate()));
            clientes.setEmail(textFieldEmail.getText());
            clientes.setStatus("False");
            dao.editar(clientes);
            tabela.limpaJtable(TableCliente);
            listar();
        }
        limparCampos();
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonImprimirActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        HabilitarCampos();
        clientes.setNomeCompleto(textFieldNome.getText());
        clientes.setContacto(textFieldContacto.getText());
        clientes.setMorada(TextFieldMorada.getText());
        clientes.setSexo(genero);
        clientes.setNrBI(textFiledNumBi.getText());
        clientes.setContrato(contrato);
        clientes.setDataNascimento(converterData(dateChooserDataNascimento.getDate()));
        clientes.setEmail(textFieldEmail.getText());
        clientes.setStatus("True");
        dao.salvar(clientes);
        tabela.limpaJtable(TableCliente);
        listar();
        limparCampos();
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void RadioButtonSexoFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSexoFemActionPerformed
        genero = "Feminino";
    }//GEN-LAST:event_RadioButtonSexoFemActionPerformed

    private void RadioButtonSexoMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSexoMascActionPerformed
        genero = "Masculino";
    }//GEN-LAST:event_RadioButtonSexoMascActionPerformed

    private void RadioButtonContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonContratoActionPerformed
        contrato = "Activo";
    }//GEN-LAST:event_RadioButtonContratoActionPerformed

    private void RadioButtonSemContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonSemContratoActionPerformed
        contrato = "Inactivo";
    }//GEN-LAST:event_RadioButtonSemContratoActionPerformed

    private void TableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClienteMouseClicked
        buttonGroupGeneroCliente.clearSelection();
        buttonGroupContrato.clearSelection();
        textFiledNumBi.setText((String) TableCliente.getValueAt(TableCliente.getSelectedRow(), 1));
        textFieldNome.setText((String) TableCliente.getValueAt(TableCliente.getSelectedRow(), 2));
        String sexo = ((String) TableCliente.getValueAt(TableCliente.getSelectedRow(), 3));
        if (sexo.equalsIgnoreCase("Feminino")) {
            RadioButtonSexoFem.setSelected(true);
            genero = "Feminino";
        } else if (sexo.equalsIgnoreCase("Masculino")) {
            RadioButtonSexoMasc.setSelected(true);
            genero = "Masculino";
        }
        String contratoh = ((String) TableCliente.getValueAt(TableCliente.getSelectedRow(), 8));
        if (contratoh.equalsIgnoreCase("Activo")) {
            RadioButtonContrato.setSelected(true);
            contrato = "Activo";
        } else if (contratoh.equalsIgnoreCase("Inactivo")) {
            RadioButtonSemContrato.setSelected(true);
            contrato = "Inactivo";
        }
        dateChooserDataNascimento.setDate(converterString((String) TableCliente.getValueAt(TableCliente.getSelectedRow(), 4)));
        TextFieldMorada.setText((String) TableCliente.getValueAt(TableCliente.getSelectedRow(), 5));
        textFieldContacto.setText((String) TableCliente.getValueAt(TableCliente.getSelectedRow(), 6));
        textFieldEmail.setText((String) TableCliente.getValueAt(TableCliente.getSelectedRow(), 7));
        cod = Integer.parseInt(String.valueOf(TableCliente.getValueAt(TableCliente.getSelectedRow(), 0)));
        desabilitarCampos();
    }//GEN-LAST:event_TableClienteMouseClicked

    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        HabilitarCampos();
        clientes.setCodCliente(cod);
        clientes.setNomeCompleto(textFieldNome.getText());
        clientes.setContacto(textFieldContacto.getText());
        clientes.setMorada(TextFieldMorada.getText());
        clientes.setSexo(genero);
        clientes.setNrBI(textFiledNumBi.getText());
        clientes.setContrato(contrato);
        clientes.setDataNascimento(converterData(dateChooserDataNascimento.getDate()));
        clientes.setEmail(textFieldEmail.getText());
        clientes.setStatus("True");
        dao.editar(clientes);
        tabela.limpaJtable(TableCliente);
        listar();
        limparCampos();
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        tabela.limpaJtable(TableCliente);
        for (Clientes c : pesquisarClientes(textFieldNome.getText())) {
            if (c.getStatus().equalsIgnoreCase("True")) {
                DefaultTableModel model = (DefaultTableModel) TableCliente.getModel();
                model.addRow(new Object[]{c.getCodCliente(), c.getNrBI(), c.getNomeCompleto(), c.getSexo(), c.getDataNascimento(), c.getMorada(), c.getContacto(), c.getEmail(), c.getContrato()});
            }
        }
        limparCampos();

    }//GEN-LAST:event_ButtonSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonImprimir;
    private javax.swing.JButton ButtonList;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JRadioButton RadioButtonContrato;
    private javax.swing.JRadioButton RadioButtonSemContrato;
    private javax.swing.JRadioButton RadioButtonSexoFem;
    private javax.swing.JRadioButton RadioButtonSexoMasc;
    private javax.swing.JTabbedPane TabbedPaneCliente;
    private javax.swing.JTable TableCliente;
    private javax.swing.JTextField TextFieldMorada;
    private javax.swing.ButtonGroup buttonGroupContrato;
    private javax.swing.ButtonGroup buttonGroupGeneroCliente;
    private com.toedter.calendar.JDateChooser dateChooserDataNascimento;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelContacto;
    private javax.swing.JLabel labelContrato;
    private javax.swing.JLabel labelDataNac;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelMorada;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumBi;
    private javax.swing.JTextField textFieldContacto;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFiledNumBi;
    // End of variables declaration//GEN-END:variables
}
