/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GeralDAO;
import static Controller.GeralDAO.listarFuncionarios;
import static Controller.GeralDAO.listarViaturas;
import Model.Funcionarios;
import Model.Viatura;
import Model.Viaturas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Almerino Buce
 */
public class FormularioViatura extends javax.swing.JPanel {
    String estado;
    /**
     * Creates new form Exemplar1
     */
    public FormularioViatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelMatricula = new javax.swing.JLabel();
        textFieldMatricula = new javax.swing.JTextField();
        labelModelo = new javax.swing.JLabel();
        textFieldModelo = new javax.swing.JTextField();
        labelTipoViatura = new javax.swing.JLabel();
        labelFabricante = new javax.swing.JLabel();
        TextFieldCor = new javax.swing.JTextField();
        labelNumChassis = new javax.swing.JLabel();
        TextFieldNumChassis = new javax.swing.JTextField();
        ButtonSalvar = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonList = new javax.swing.JButton();
        TabbedPaneViatura = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableViatura = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ButtonSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelCodigoMotor = new javax.swing.JLabel();
        TextFieldCodMotor = new javax.swing.JTextField();
        labelCor = new javax.swing.JLabel();
        TextFieldFabricante = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox();
        radioButtonOperacional = new javax.swing.JRadioButton();
        radioButtonAvariado = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(940, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1254, 798));

        labelMatricula.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelMatricula.setText("Matricula");

        textFieldMatricula.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N

        labelModelo.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelModelo.setText("Modelo");

        textFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldModeloActionPerformed(evt);
            }
        });

        labelTipoViatura.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelTipoViatura.setText("Tipo");

        labelFabricante.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelFabricante.setText("Fabricante");

        labelNumChassis.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelNumChassis.setText("Codigo de chassi");

        TextFieldNumChassis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNumChassisActionPerformed(evt);
            }
        });

        ButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Add1.png"))); // NOI18N
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        ButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Update.png"))); // NOI18N

        ButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonList.setBackground(new java.awt.Color(255, 255, 255));
        ButtonList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/List.png"))); // NOI18N
        ButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListActionPerformed(evt);
            }
        });

        TableViatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Codigo do motor", "Codigo de chassi", "Fabricante", "Modelo", "Tipo", "Cor", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableViatura);

        TabbedPaneViatura.addTab("Tabela de Viaturas", jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(129, 190, 234));

        ButtonSearch.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel3.setText("Viatura");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelCodigoMotor.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelCodigoMotor.setText("Codigo do motor");

        TextFieldCodMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCodMotorActionPerformed(evt);
            }
        });

        labelCor.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelCor.setText("Cor");

        labelEstado.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        labelEstado.setText("Estado ");

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o tipo", "Sedan", "Hatchback", "SUV", "Camiao", "Camioneta", "Van", "Mini-Van", "Autocarro", "Mini-Autocarro", "Outros", " " }));

        buttonGroupEstado.add(radioButtonOperacional);
        radioButtonOperacional.setText("Operacional");
        radioButtonOperacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonOperacionalActionPerformed(evt);
            }
        });

        buttonGroupEstado.add(radioButtonAvariado);
        radioButtonAvariado.setText("Avariado");
        radioButtonAvariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAvariadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelMatricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TabbedPaneViatura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodigoMotor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldCodMotor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFabricante)
                                    .addComponent(labelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(TextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextFieldNumChassis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelNumChassis, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(radioButtonOperacional)
                                                        .addGap(30, 30, 30)
                                                        .addComponent(radioButtonAvariado)))
                                                .addGap(0, 0, 0))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelTipoViatura, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))))))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoViatura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumChassis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNumChassis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButtonOperacional)
                            .addComponent(radioButtonAvariado))))
                .addGap(12, 12, 12)
                .addComponent(labelCodigoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldCodMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonList, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TabbedPaneViatura, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldModeloActionPerformed

    private void TextFieldNumChassisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNumChassisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNumChassisActionPerformed

    private void ButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListActionPerformed
        for (Viaturas v : listarViaturas()) {
            DefaultTableModel model = (DefaultTableModel) TableViatura.getModel();
            model.addRow(new Object[]{v.getMatricula(), v.getCodMotor(), v.getCodChassi(), v.getFabricante(), v.getModelo(), v.getTipo(), v.getCor(), v.getEstado()});
        }
    }//GEN-LAST:event_ButtonListActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void TextFieldCodMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCodMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCodMotorActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        Viaturas viaturas = new Viaturas();
        GeralDAO<Viaturas> gd = new GeralDAO<>();
        viaturas.setMatricula(textFieldMatricula.getText());
        viaturas.setModelo(textFieldModelo.getText());
        viaturas.setFabricante(TextFieldFabricante.getText());
        viaturas.setCor(TextFieldCor.getText());
        viaturas.setCodMotor(TextFieldCodMotor.getText());
        viaturas.setTipo(comboBoxTipo.getSelectedItem().toString());
        viaturas.setCodChassi(TextFieldNumChassis.getText());
        viaturas.setEstado(estado);

        gd.salvar(viaturas);
//        DefaultTableModel model = (DefaultTableModel) TableViatura.getModel();
//        model.addRow(new Object[]{textFieldMatricula.getText(), TextFieldCodMotor.getText(), TextFieldNumChassis.getText(),
//            TextFieldFabricante.getText(), textFieldModelo.getText(), comboBoxTipo.getSelectedItem().toString(), TextFieldCor.getText(), TextFieldEstado.getText()});

    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void radioButtonOperacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonOperacionalActionPerformed
        estado = "Operacional";
    }//GEN-LAST:event_radioButtonOperacionalActionPerformed

    private void radioButtonAvariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAvariadoActionPerformed
        estado = "Avariado";
    }//GEN-LAST:event_radioButtonAvariadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonList;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JTabbedPane TabbedPaneViatura;
    private javax.swing.JTable TableViatura;
    private javax.swing.JTextField TextFieldCodMotor;
    private javax.swing.JTextField TextFieldCor;
    private javax.swing.JTextField TextFieldFabricante;
    private javax.swing.JTextField TextFieldNumChassis;
    private javax.swing.ButtonGroup buttonGroupEstado;
    private javax.swing.JComboBox comboBoxTipo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCodigoMotor;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFabricante;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelNumChassis;
    private javax.swing.JLabel labelTipoViatura;
    private javax.swing.JRadioButton radioButtonAvariado;
    private javax.swing.JRadioButton radioButtonOperacional;
    private javax.swing.JTextField textFieldMatricula;
    private javax.swing.JTextField textFieldModelo;
    // End of variables declaration//GEN-END:variables
}
