/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author Almerino Buce
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        this.setVisible(false);
        dispose();
        this.setFocusable(true);
        this.setUndecorated(true);
        //jButton1.setBackground(null);
        cardLayout = (CardLayout) painelCard.getLayout();
    }
    ExemplarVermelho exemplarVermelho = new ExemplarVermelho();
    ExemplarVerde exemplarVerde = new ExemplarVerde();
    ExemplarBranco exemplarBranco = new ExemplarBranco();
    ExemplarPreto exemplarPreto = new ExemplarPreto();
    FormularioCliente formCli = new FormularioCliente();
    CardLayout cardLayout;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskTopPanePrincipal = new javax.swing.JDesktopPane();
        painelLeft = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        painelUtlizador = new javax.swing.JPanel();
        buttonTeste = new javax.swing.JButton();
        buttonTeste1 = new javax.swing.JButton();
        buttonTeste2 = new javax.swing.JButton();
        buttonTeste3 = new javax.swing.JButton();
        painelCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelLeft.setBackground(new java.awt.Color(102, 255, 51));

        jPanel6.setBackground(new java.awt.Color(98, 153, 194));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        painelUtlizador.setBackground(new java.awt.Color(129, 190, 234));
        painelUtlizador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                painelUtlizadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                painelUtlizadorFocusLost(evt);
            }
        });

        buttonTeste.setBackground(null);
        buttonTeste.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        buttonTeste.setText("Teste Vermelho");
        buttonTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTesteActionPerformed(evt);
            }
        });

        buttonTeste1.setBackground(null);
        buttonTeste1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        buttonTeste1.setText("Teste Verde");
        buttonTeste1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTeste1ActionPerformed(evt);
            }
        });

        buttonTeste2.setBackground(null);
        buttonTeste2.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        buttonTeste2.setText("Teste Preto");
        buttonTeste2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTeste2ActionPerformed(evt);
            }
        });

        buttonTeste3.setBackground(null);
        buttonTeste3.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        buttonTeste3.setText("Teste Branco");
        buttonTeste3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTeste3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelUtlizadorLayout = new javax.swing.GroupLayout(painelUtlizador);
        painelUtlizador.setLayout(painelUtlizadorLayout);
        painelUtlizadorLayout.setHorizontalGroup(
            painelUtlizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUtlizadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelUtlizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTeste2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(painelUtlizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelUtlizadorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buttonTeste1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(painelUtlizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelUtlizadorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buttonTeste3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        painelUtlizadorLayout.setVerticalGroup(
            painelUtlizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelUtlizadorLayout.createSequentialGroup()
                .addContainerGap(404, Short.MAX_VALUE)
                .addComponent(buttonTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(buttonTeste2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(painelUtlizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelUtlizadorLayout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(buttonTeste1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(577, Short.MAX_VALUE)))
            .addGroup(painelUtlizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelUtlizadorLayout.createSequentialGroup()
                    .addGap(262, 262, 262)
                    .addComponent(buttonTeste3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(418, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 250, Short.MAX_VALUE)
                .addComponent(painelUtlizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(painelUtlizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelCard.setBackground(new java.awt.Color(255, 255, 255));
        painelCard.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2021-bugatti-chiron-super-sport-300.jpg"))); // NOI18N
        painelCard.add(jLabel1, "card2");

        javax.swing.GroupLayout painelLeftLayout = new javax.swing.GroupLayout(painelLeft);
        painelLeft.setLayout(painelLeftLayout);
        painelLeftLayout.setHorizontalGroup(
            painelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLeftLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(painelCard, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelLeftLayout.setVerticalGroup(
            painelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(painelCard, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout deskTopPanePrincipalLayout = new javax.swing.GroupLayout(deskTopPanePrincipal);
        deskTopPanePrincipal.setLayout(deskTopPanePrincipalLayout);
        deskTopPanePrincipalLayout.setHorizontalGroup(
            deskTopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        deskTopPanePrincipalLayout.setVerticalGroup(
            deskTopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        deskTopPanePrincipal.setLayer(painelLeft, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskTopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskTopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void painelUtlizadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_painelUtlizadorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_painelUtlizadorFocusGained

    private void painelUtlizadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_painelUtlizadorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_painelUtlizadorFocusLost

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void buttonTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTesteActionPerformed
        painelCard.add(exemplarVermelho, "exemplarVermelho");
        cardLayout.show(painelCard, "exemplarVermelho");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_buttonTesteActionPerformed

    private void buttonTeste1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTeste1ActionPerformed
        painelCard.add(exemplarVerde, "exemplarVerde");
        cardLayout.show(painelCard, "exemplarVerde");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_buttonTeste1ActionPerformed

    private void buttonTeste2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTeste2ActionPerformed
        painelCard.add(exemplarPreto, "exemplarPreto");
        cardLayout.show(painelCard, "exemplarPreto");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_buttonTeste2ActionPerformed

    private void buttonTeste3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTeste3ActionPerformed
        painelCard.add(formCli, "exemplarBranco");
        cardLayout.show(painelCard, "exemplarBranco");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_buttonTeste3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTeste;
    private javax.swing.JButton buttonTeste1;
    private javax.swing.JButton buttonTeste2;
    private javax.swing.JButton buttonTeste3;
    private javax.swing.JDesktopPane deskTopPanePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel painelCard;
    private javax.swing.JPanel painelLeft;
    private javax.swing.JPanel painelUtlizador;
    // End of variables declaration//GEN-END:variables
}
